/**
 * BUILD-TIME tenant app configuration.
 * Baked into the binary; changing any of these requires a new store build.
 * Contains NO secrets — everything here is visible to anyone who downloads the app.
 *
 * Runtime branding (colors, logo, support email) is NOT here; it is fetched from
 * GET /api/v1/apps/bootstrap and can change without a release.
 */
export type TenantBuildConfig = {
  /** Immutable tenant UUID (public). Written at provisioning; used to namespace Cognito usernames (ADR-006). */
  tenantId?: string;
  /** Folder name; selects this config via APP_TENANT=<slug>. */
  slug: string;
  /** Public TenantApp.appKey sent as X-App-Key. Identifies context — NOT authorization. */
  appKeys: { ios: string; android: string };
  /** Store display name (home screen label). */
  appName: string;
  /** Deep-link scheme, unique per tenant. */
  scheme: string;
  ios: { bundleIdentifier: string; appleTeamId?: string };
  android: { package: string };
  /** Paths relative to this tenant folder. Generated by the provisioning service in the future. */
  assets: { icon: string; splash: string; adaptiveIcon?: string };
  /** Splash background only — a build-time asset concern, not runtime theming. */
  splashBackgroundColor: string;
  /** EAS project per tenant app (store identity), filled at provisioning time. */
  easProjectId?: string;
  version: string;
  buildNumber: number;
};
